### ISSUE TITLE
translation of international_languages

### ISSUE THREAD

**Issue by satomicchy** [hyperledger/fabric-docs-i18n#50]
https://github.com/hyperledger/fabric-docs-i18n/blob/release-2.2/docs/locale/ja_JP/source/international_languages.md

**Comment by shimos** [comment]
Would like to work on this

**Comment by Naoya-Horiguchi** [comment]
The PR #68 was merged, so I close this issue. Thank you for your work.

BTW, this repository chooses "rebase and merge" operation when merging, so no merge commit is generated. We have to add the magic word like "Resolves #50" in the individual patch, not in the pull request message in order to automatically close the issue.
